const esc = (value) => String(value ?? '').replace(/[&<>"']/g,(char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const MAX_FILE = 2 * 1024 * 1024,MAX_TOTAL = 20 * 1024 * 1024;
const formats = new Set(['txt','md','csv','tsv','pdf','docx','xlsx','jpg','jpeg','png']);
const size = (bytes) => `${Number(bytes).toLocaleString('zh-CN')} 字节（${(Number(bytes) / 1024 / 1024).toFixed(2)} MiB）`;
const filename = (value) => String(value || '').split(/[\\/]/).pop();
function base64(buffer) {const bytes = new Uint8Array(buffer);let binary = '';for (let index = 0;index < bytes.length;index += 16384) binary += String.fromCharCode(...bytes.subarray(index,index + 16384));return btoa(binary);}
export function createAttachmentsWorkspace({getState,getElement,request,post,render,toast,refreshMatter,ensureIdentity,preserveArtifact=() => {}}) {
  const records = new Map(),downloads = new Set();
  const current = () => getState().current;
  const previewKey = (record,id) => record?.sheetNames?.get(id) ? JSON.stringify([id,record.sheetNames.get(id)]) : id;
  const previewFor = (record,id) => record?.previews?.get(previewKey(record,id));
  const recordFor = (id) => {if (!records.has(id)) records.set(id,{open:false,data:null,file:null,baseVersion:null,error:null,reading:false,uploading:false,attempted:false});return records.get(id);};
  const own = (id,epoch,selection) => current()?.id === id && getState().identityEpoch === epoch && getState().selection === selection;
  const keepDom = () => Boolean(current() && getElement('.attachments-panel') && (records.get(current().id)?.open || records.get(current().id)?.file || globalThis.document?.activeElement?.closest('.attachments-panel')));
  function noteVersion() {const matter = current(),record = records.get(matter?.id),label = getElement('#attachments-stale');if (!matter || !record || !label) return;const stale = record.data && (record.data.version !== matter.version || record.data.input_revision !== matter.revision_no);label.hidden = !stale && !record.error && !(record.file && record.baseVersion !== matter.version);label.textContent = record.error || `当前已读事项版本 ${matter.version}／修订 ${matter.revision_no}；附件列表来自版本 ${record.data?.version ?? '未读'}，所选文件保存基版 ${record.baseVersion ?? '未选择'}。后台不替换文件或基版，请明确读回核对后采用附件列表版本。`;}
  async function read(id) {
    if (current()?.id !== id) return;const record = recordFor(id);if (record.reading || record.uploading) return;const epoch = getState().identityEpoch,selection = getState().selection;record.reading = true;record.attempted = true;render();
    try {const data = await request(`/api/matters/${encodeURIComponent(id)}/attachments`);if (!own(id,epoch,selection)) return;record.data = data;record.error = null;}
    catch (error) {if (own(id,epoch,selection)) {record.error = error.message || '原始附件列表未读回；已选文件与所有人工稿保留。';if ([401,403,404].includes(error.status)) record.data = null;}}
    finally {record.reading = false;if (own(id,epoch,selection)) {render();noteVersion();}}
  }
  function input(element) {
    if (element.dataset?.attachmentSheet) {const record = recordFor(current().id);record.sheetNames ||= new Map();record.sheetNames.set(element.dataset.attachmentSheet,element.value);render();return true;}
    if (element.dataset?.attachmentText) {const record = records.get(current()?.id),preview = previewFor(record,element.dataset.attachmentText);if (preview) {preview.text = element.value;preview.dirty = true;}return true;}
    if (element.id !== 'attachment-file') return false;const matter = current();if (!matter) return true;const record = recordFor(matter.id),file = element.files?.[0];if (!file) return true;
    const name = filename(file.name),format = name.split('.').pop().toLowerCase();
    if (!formats.has(format) || !name || name.length > 200 || file.size > MAX_FILE || file.size < 1) {record.error = '请选择单件1字节至2MiB、文件名最多200字的 TXT／MD／CSV／TSV／PDF／DOCX／XLSX／JPG／JPEG／PNG 原件；原所选文件保留，不截断、不识别内容。';render();return true;}
    record.file = file;record.baseVersion = matter.version;record.open = true;record.error = null;render();return true;
  }
  async function readText(attachmentId) {
    const matter = current();if (!matter || getState().busy) return;const record = recordFor(matter.id),epoch = getState().identityEpoch,selection = getState().selection;
    const sheetName = record.sheetNames?.get(attachmentId),key = previewKey(record,attachmentId);record.previews ||= new Map();record.reading = true;record.error = null;render();
    try {const result = await request(`/api/matters/${encodeURIComponent(matter.id)}/attachments/${encodeURIComponent(attachmentId)}/text${sheetName ? `?sheet_name=${encodeURIComponent(sheetName)}` : ''}`);if (!own(matter.id,epoch,selection)) return;if (result.worksheets) {record.worksheetLists ||= new Map();record.worksheetLists.set(attachmentId,result.worksheets);}if (result.needs_sheet_selection) return;let preview = record.previews.get(key);if (!preview) {preview = {text:result.text,baseVersion:result.version,dirty:false,saved:false};record.previews.set(key,preview);}preview.remote = result;}
    catch (error) {if (own(matter.id,epoch,selection)) record.error = error.message || '正文候选未读回；原件和人工编辑保留。';}
    finally {record.reading = false;if (own(matter.id,epoch,selection)) render();}
  }
  async function saveText(attachmentId) {
    const matter = current(),record = records.get(matter?.id),preview = previewFor(record,attachmentId);if (!matter || !preview || getState().busy || (preview.saved && !preview.dirty)) return;
    const epoch = getState().identityEpoch,selection = getState().selection;preserveArtifact();
    await post(`/api/matters/${encodeURIComponent(matter.id)}/attachments/${encodeURIComponent(attachmentId)}/text`,{expected_version:preview.baseVersion,text:preview.text,...(preview.remote.sheet_name ? {sheet_name:preview.remote.sheet_name} : {})},async (result)=>{if (!own(matter.id,epoch,selection)) return;preview.baseVersion = result.version;preview.remote.version = result.version;preview.saved = true;preview.dirty = false;record.error = null;toast('正文片段已另存为本人文字来源，未确认事实、未发送模型，原件与人工稿保留。');await refreshMatter(matter.id,selection);});
  }
  function textMarkup(record,item,disabled) {
    const supported = ['docx','xlsx','txt','md','csv','tsv'].includes(item.declared_format),preview = previewFor(record,item.id),sheets = record.worksheetLists?.get(item.id),chosen = record.sheetNames?.get(item.id);
    const sheetMarkup = sheets ? `<label class="field-label" for="attachment-sheet-${esc(item.id)}">明确工作表（其他表不读取；切换保留各表未保存文字）</label><select id="attachment-sheet-${esc(item.id)}" data-attachment-sheet="${esc(item.id)}" ${disabled}><option value="">请选择一个实际工作表</option>${sheets.map(sheet=>`<option value="${esc(sheet.name)}" ${chosen === sheet.name ? 'selected' : ''}>${esc(sheet.name)}${sheet.state !== 'visible' ? ' · 隐藏表' : ''}</option>`).join('')}</select>` : '';
    if (!supported) return '<p class="small muted">此格式当前只存原件，正文／OCR未读取，可人工补充文字继续。</p>';
    return `${sheetMarkup}<button class="button" type="button" data-action="attachments-text-read" data-attachment-id="${esc(item.id)}" ${disabled}>${item.declared_format === 'xlsx' ? sheets ? '读取所选工作表文字' : '读取工作表目录（不读单元格）' : '明确读取正文候选'}</button>${preview ? `<div class="attachment-text-preview"><label class="field-label" for="attachment-text-${esc(item.id)}">本地正文候选（核对后另存片段）</label><textarea id="attachment-text-${esc(item.id)}" data-attachment-text="${esc(item.id)}" maxlength="12000" ${disabled}>${esc(preview.text)}</textarea><p class="scope-note">${esc(preview.remote.scope)}${preview.remote.truncated ? ' 已截断：最多12000字／500正文段落，后续内容未列入。' : ''} ${(preview.remote.unread || []).map(esc).join('；')}</p><p class="small ${preview.dirty || preview.baseVersion !== current()?.version ? 'dirty-note' : 'muted'}">保存基版 ${esc(preview.baseVersion)} · 已读事项版本 ${esc(preview.remote.version)}${preview.dirty ? ' · 有人工编辑' : preview.saved ? ' · 片段已保存' : ' · 候选尚未转存'}</p><div class="artifact-toolbar"><button class="button" type="button" data-action="attachments-text-save" data-attachment-id="${esc(item.id)}" ${disabled || (preview.saved && !preview.dirty) ? 'disabled' : ''}>核对后另存正文片段来源</button><button class="button quiet" type="button" data-action="attachments-text-adopt" data-attachment-id="${esc(item.id)}" ${disabled}>核对后采用已读基版（正文保留）</button></div><p class="scope-note">另存片段不会改事实或替代旧来源；如要替代旧片段，请核对来源引用控制。修改正文后不沿用原件段落定位。</p>${preview.remote.positions?.length ? `<details><summary class="details-toggle">解析位置（Word正文段落／Excel原行，非页码）</summary><ul>${preview.remote.positions.map(position=>`<li>候选行 ${esc(position.start_line)}–${esc(position.end_line)}：${esc(position.position)}</li>`).join('')}</ul></details>` : ''}</div>` : ''}`;
  }
  function toggle(element) {if (element.id !== 'attachments-details' || !element.isConnected || !current()) return;const record = recordFor(current().id);record.open = element.open;if (record.open && !record.attempted) read(current().id);}
  async function save() {
    const matter = current(),record = records.get(matter?.id);if (!matter || !record?.file || getState().busy || record.uploading || record.reading) return;
    const file = record.file;if (!record.data) {record.error = '先明确读回原件列表与当前容量，再保存；所选文件保留。';render();return;}
    const total = (record.data.attachments || []).reduce((sum,item) => sum + item.byte_count,0);if (total + file.size > MAX_TOTAL) {record.error = '已读列表与本文件合计超本事项20MiB，整件暂不上传，不截断；可读回核对容量。';render();return;}
    const epoch = getState().identityEpoch,selection = getState().selection,baseVersion = record.baseVersion;preserveArtifact();record.uploading = true;record.error = null;render();let saved = false;
    try {
      const buffer = await file.arrayBuffer();if (!own(matter.id,epoch,selection) || record.file !== file) return;if (buffer.byteLength !== file.size || buffer.byteLength > MAX_FILE) throw new Error('文件读取大小不一致，未上传；所选文件保留。');
      await post(`/api/matters/${encodeURIComponent(matter.id)}/attachments`,{expected_version:baseVersion,filename:filename(file.name),content_base64:base64(buffer)},async (data) => {if (!own(matter.id,epoch,selection)) return;saved = true;record.data = data;record.file = null;record.baseVersion = null;record.error = null;toast('原始附件已私有保存，未读取识别、未进入文字来源或模型，也未分享。');await refreshMatter(matter.id,selection);});
      if (!saved && own(matter.id,epoch,selection)) record.error = '原件保存未确认，所选文件保留；请读回附件列表核对后明确采用其保存基版。';
    } catch (error) {if (own(matter.id,epoch,selection)) record.error = error.message || '原件读取或保存未完成，所选文件与人工稿保留。';}
    finally {record.uploading = false;if (own(matter.id,epoch,selection)) {render();noteVersion();}}
  }
  async function download(attachmentId) {
    const matter = current(),record = records.get(matter?.id),attachment = record?.data?.attachments?.find((item) => item.id === attachmentId);if (!matter || !attachment || getState().busy || downloads.has(attachmentId)) return;
    const epoch = getState().identityEpoch,selection = getState().selection,controller = new AbortController(),timeout = setTimeout(() => controller.abort(),30000);downloads.add(attachmentId);render();
    try {
      if (!await ensureIdentity() || !own(matter.id,epoch,selection)) return;
      const response = await fetch(`/api/matters/${encodeURIComponent(matter.id)}/attachments/${encodeURIComponent(attachmentId)}/download`,{credentials:'same-origin',signal:controller.signal});
      if (!response.ok) {let body = {};try {body = await response.json();}catch {}throw {status:response.status,message:body.error?.message || body.message || '当前原始附件不可下载。'};}
      const blob = await response.blob();if (!own(matter.id,epoch,selection)) return;const url = URL.createObjectURL(blob),link = document.createElement('a');link.href = url;link.download = filename(attachment.filename);link.click();setTimeout(() => URL.revokeObjectURL(url),1000);toast('已请求浏览器下载所选已保存原件；不代表已查看、识别或业务核验。');
    } catch (error) {if (own(matter.id,epoch,selection)) {if (error.status === 401) {try {await ensureIdentity();}catch {}if (!own(matter.id,epoch,selection)) return;}if ([403,404].includes(error.status) && record.data) record.data.attachments = record.data.attachments.filter((item) => item.id !== attachmentId);record.error = error.name === 'AbortError' ? '原件下载请求已超时；待保存文件及人工稿保留，可稍后重试。' : error.message || '原件下载未完成，人工稿保留。';}}
    finally {clearTimeout(timeout);downloads.delete(attachmentId);if (own(matter.id,epoch,selection)) render();}
  }
  function markup(matter) {
    const record = recordFor(matter.id),data = record.data,busy = getState().busy || record.reading || record.uploading,disabled = busy ? 'disabled' : '',total = (data?.attachments || []).reduce((sum,item) => sum + item.byte_count,0);
    return `<section class="panel attachments-panel"><details id="attachments-details" ${record.open ? 'open' : ''}><summary class="details-toggle">私有原附件 · 正文候选与转存</summary><p class="scope-note">单件最多2MiB，本事项最多20MiB。保存仅存原始字节，不运行文件、不自动发送或分享。DOCX正文、XLSX明确选定工作表及UTF-8文字可本地读取，核对转存后才成为文字来源；PDF／图片／OCR仍未读取。XLSX公式不计算，格式值与缺项须核对，不读缓存、不补零、不截断数值。TXT／MD／CSV／TSV／PDF／DOCX／XLSX／JPG／JPEG／PNG 仅按文件名声明格式，不代表内容或安全已核验。旧文字来源的文件声明不能追认为原件。</p><div class="artifact-toolbar"><button class="button quiet" type="button" data-action="attachments-read" ${disabled}>明确读回附件列表与当前容量</button>${record.file && data ? `<button class="button quiet" type="button" data-action="attachments-adopt" ${disabled}>核对列表后采用已读保存基版 ${esc(data.version)}</button>` : ''}</div><p id="attachments-stale" class="small dirty-note" role="status" hidden></p>${record.error ? `<p class="small dirty-note">${esc(record.error)}</p>` : ''}${record.reading ? '<p class="small muted">正在读取已存列表，未上传所选文件。</p>' : ''}<label class="field-label" for="attachment-file">选择待保存原件（不会自动上传）</label><input id="attachment-file" type="file" accept=".txt,.md,.csv,.tsv,.pdf,.docx,.xlsx,.jpg,.jpeg,.png" ${disabled}>${record.file ? `<p class="small dirty-note">未保存原件：${esc(filename(record.file.name))} · ${esc(size(record.file.size))} · 保存基版 ${esc(record.baseVersion)}。原文字与人工稿保留。</p><div class="artifact-toolbar"><button class="button" type="button" data-action="attachments-save" ${disabled}>明确保存所选原件</button><button class="button quiet" type="button" data-action="attachments-clear" ${disabled}>清除待保存文件选择</button></div>` : '<p class="small muted">尚未选择待保存原件；只选择不上传，不替换已有来源或稿件。</p>'}${record.uploading ? '<p class="small muted">正在读取并请求保存完整原件；不识别内容，不截断。</p>' : ''}${data ? `<p class="scope-note">${esc(data.scope)} · 列表版本 ${esc(data.version)}／输入修订 ${esc(data.input_revision)}。已存 ${esc(size(total))}；仅本次读回容量，以服务器保存核对为准。</p><div class="attachments-list">${(data.attachments || []).map((item) => `<article class="attachment-record"><div class="panel-head"><strong>${esc(item.filename)}</strong><button class="button quiet" type="button" data-action="attachments-download" data-attachment-id="${esc(item.id)}" ${disabled || downloads.has(item.id) ? 'disabled' : ''}>下载此已存原件</button></div><p class="small muted">声明格式 ${esc(item.declared_format)} · ${esc(size(item.byte_count))}<br>上传者 ${esc(item.uploaded_by)} · ${esc(item.uploaded_at)}</p><details><summary class="details-toggle">实际保存标识与完整性摘要</summary><p class="small muted">附件ID ${esc(item.id)}<br>SHA-256 <code>${esc(item.sha256)}</code></p></details>${textMarkup(record,item,disabled)}</article>`).join('') || '<p class="small muted">此已读列表尚无保存原件，不推定没有材料。</p>'}</div>` : '<p class="small muted">尚未读回原件列表，不推定原件已保存或不存在。</p>'}</details></section>`;
  }
  function action(name,button) {if (!name?.startsWith('attachments-')) return false;const matter = current();if (!matter) return true;const record = recordFor(matter.id);if (name === 'attachments-read') read(matter.id);else if (name === 'attachments-save') save();else if (name === 'attachments-text-read') readText(button.dataset.attachmentId);else if (name === 'attachments-text-save') saveText(button.dataset.attachmentId);else if (name === 'attachments-text-adopt') {const preview = previewFor(record,button.dataset.attachmentId);if (preview?.remote) {preview.baseVersion = preview.remote.version;record.error = null;render();toast('采用已读正文候选基版，编辑文字保留。');}}else if (name === 'attachments-download') download(button.dataset.attachmentId);else if (name === 'attachments-clear') {record.file = null;record.baseVersion = null;record.error = null;render();}else if (name === 'attachments-adopt' && record.file && record.data) {record.baseVersion = record.data.version;record.error = null;toast('仅采用本人已核对的附件列表保存版本；文件与文字保持原值。');render();}else return false;return true;}
  return {read,input,toggle,markup,action,keepDom,noteVersion,noteError:(message) => {const record = records.get(current()?.id);if (record) {record.error = message;noteVersion();}},isDirty:() => [...records.values()].some((record) => Boolean(record.file) || [...(record.previews?.values() || [])].some(preview=>preview.dirty)),clear:() => {records.clear();downloads.clear();}};
}
