const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function conversationMarkup(m,{draft,busy,configured,time,scope,category=''}) {
  const held=['paused','handoff'].includes(m.assistant_status),blocked=m.model_disclosure_blocked;
  const mode=held||blocked?'save':draft.messageMode??(configured?'model':'template');
  const action=(m.actions||[]).at(-1),status=held?(m.assistant_status==='handoff'?'由你接手；补充仍可保存':'已暂停；补充仍可保存'):m.assistant_status==='processing'?(action?.kind==='prepare_model'?'交融正在整理当前上下文':'正在整理准备稿'):blocked?'等待你核对来源范围':m.conversation_questions?.length?'有几个具体问题需要你补充':'已有内容已保存，可以接着说';
  const messages=(m.sources||[]).slice(-20).map((s,i)=>({at:s.recorded_at,order:i,html:`<article class="conversation-bubble user-message"><div class="small muted">${s.kind==='user_text'?'你的原话':'已提供的来源'} · ${esc(time(s.recorded_at))}${s.source_state!=='usable'?` · ${s.source_state==='withheld'?'暂不用':'旧版原话'}`:''}</div><p>${esc(s.text)}</p></article>`}));
  for(const a of (m.artifacts||[]).slice(0,5))messages.push({at:a.created_at,order:100,html:`<article class="conversation-bubble result-message"><div class="small muted">${a.status==='human_saved'?'你保存的成果':a.status==='model_draft'?'交融候选成果':'本地准备成果'} · ${esc(time(a.created_at))}</div><strong>${esc(a.title)}</strong><p>${esc(a.content.slice(0,600))}${a.content.length>600?'…':''}</p><div class="artifact-toolbar"><button class="button" data-conversation-artifact="${esc(a.id)}" ${busy?'disabled':''}>打开并编辑成果</button><small class="${a.stale?'dirty-note':'muted'}">v${esc(a.version)}${a.stale?' · 依据已变化，保留历史':' · 已保存'}${a.status==='model_draft'?' · 内容待核':''}</small></div></article>`});
  messages.sort((a,b)=>String(a.at).localeCompare(String(b.at))||a.order-b.order);
  const failed=action?.status==='failed'?`<p class="inline-error">${esc(action.error||'整理未完成，原内容保留。')}</p>`:'';
  return `<section class="panel conversation-panel" aria-label="事项对话"><div class="conversation-status" role="status"><span class="status-dot"></span><strong>${esc(status)}</strong></div><div class="conversation-log">${messages.map(x=>x.html).join('')}${!messages.length?'<p class="small muted">直接说需要办的事情，我会沿同一目标整理。</p>':''}</div>${m.sources?.length>20||m.artifacts?.length>5?'<p class="small muted">显示最近20条来源及5份成果；完整已存记录在下方办理区。</p>':''}${m.conversation_questions?.length?`<div class="conversation-questions"><strong>接下来需要你补充</strong><ul>${m.conversation_questions.slice(0,3).map((q,i)=>`<li>${esc(q)} <button class="button quiet" type="button" data-action="question-waiting" data-question-index="${i}" ${busy?'disabled':''}>留作本人待办</button></li>`).join('')}</ul>${m.conversation_questions.length>3?'<small>其余问题保留在成果正文。</small>':''}</div>`:''}${failed}${category}<div class="artifact-toolbar"><button class="button quiet" data-action="open-title-context" ${busy?'disabled':''}>参考已有事项 · ${m.private_title_context_enabled?'已允许标题':'默认关闭'}</button></div><form id="conversation-form"><label class="field-label" for="conversation-message">接着说，或告诉助理要怎么调整</label><textarea id="conversation-message" name="text" maxlength="12000" required placeholder="例如：出发改到下午，先整理用车需求；午餐是否留饭还需要问一下。" ${busy?'disabled':''}>${esc(draft.messageText||'')}</textarea><div class="composer-toolbar"><select id="conversation-mode" name="mode" aria-label="这条补充的处理方式" ${busy||held||blocked?'disabled':''}><option value="model" ${mode==='model'?'selected':''} ${configured?'':'disabled'}>发送并交融整理${configured?'':'（待配置）'}</option><option value="template" ${mode==='template'?'selected':''}>发送并本地整理</option><option value="save" ${mode==='save'?'selected':''}>只保存补充</option></select><button class="button primary" type="submit" ${busy?'disabled':''}>${busy?'正在保存…':mode==='save'?'保存这条补充':mode==='model'?'发送并交融整理':'发送并本地整理'}</button></div><p class="small muted">${mode==='model'?esc(scope):mode==='save'?'只保存本人原话；保持暂停／接手，不触发整理。':'只整理本地模板，不调用模型。'} 补充是原话，已核事实仍需明确修正；不登记批准或执行。</p></form></section>`;
}
