const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createPrivateContext({getState,request,post,render,toast,refreshMatter}) {
  const records=new Map();const rec=id=>{if(!records.has(id))records.set(id,{open:false,data:null,enabled:null,dirty:false,loading:false,error:null});return records.get(id);};
  async function read(id) {const s=getState(),r=rec(id),epoch=s.identityEpoch,selection=s.selection;if(r.loading)return;r.loading=true;
    try{const data=await request(`/api/matters/${encodeURIComponent(id)}/related-tasks/context`);if(epoch!==getState().identityEpoch||selection!==getState().selection||getState().current?.id!==id)return;r.data=data;if(!r.dirty)r.enabled=data.enabled;r.error=null;}
    catch(e){if(epoch===getState().identityEpoch&&selection===getState().selection)r.error=e.message;}
    finally{r.loading=false;if(epoch===getState().identityEpoch&&selection===getState().selection&&getState().current?.id===id)render();}}
  function markup(m) {const s=getState(),r=rec(m.id),enabled=r.dirty?r.enabled:m.private_title_context_enabled;
    return `<details class="private-context-panel" ${r.open?'open':''}><summary class="details-toggle">参考本人已有事项（可选） · ${m.private_title_context_enabled?'已允许标题比对':'默认关闭'}</summary><p class="scope-note">开启后，后续明确的交融整理可参考最近最多10份本人其他事项的目标标题原文（可能包含个人信息）。不发送那些事项的事实、资料正文或其他人内容，不后台自动调用；已发送标题无法召回。换版或暂不用的关联依据须重核。</p><button class="button quiet" data-action="private-context-read" ${s.busy||r.loading?'disabled':''}>读取本次可参考标题（本机，不调用模型）</button>${r.error?`<p class="dirty-note">${esc(r.error)}</p>`:''}${r.data?`<ul>${r.data.items.map(i=>`<li>${esc(i.goal_text)}</li>`).join('')||'<li>本次没有可参考标题。</li>'}</ul><p class="small muted">本页列表为已读取范围，模型请求登记时重新固定当时可用范围；可沿原模型输入预览核对。仅参考不代表已确认同一事件。</p>`:''}<label class="field-label"><input type="checkbox" data-private-context-enable ${enabled?'checked':''} ${s.busy?'disabled':''}> 允许本事项后续明确交融整理发送最多10份本人其他事项的目标标题</label><button class="button quiet" data-action="private-context-save" ${s.busy?'disabled':''}>保存标题参考许可</button>${r.dirty?'<p class="dirty-note">许可修改尚未保存；原人工编辑保留。</p>':''}</details>`;}
  return {markup,input:el=>{if(el.dataset.privateContextEnable===undefined||!getState().current)return false;const r=rec(getState().current.id);r.enabled=el.checked;r.dirty=true;return true;},toggle:el=>{if(el.matches('.private-context-panel')&&el.isConnected&&getState().current)rec(getState().current.id).open=el.open;},action:name=>{if(!name?.startsWith('private-context-'))return false;const s=getState(),m=s.current;if(!m)return true;if(name==='private-context-read'){read(m.id);return true;}const r=rec(m.id),selection=s.selection;post(`/api/matters/${encodeURIComponent(m.id)}/related-tasks/context`,{expected_version:m.version,input_revision:m.revision_no,enabled:Boolean(r.dirty?r.enabled:m.private_title_context_enabled)},async()=>{r.dirty=false;toast('标题参考许可已保存，没有模型调用；原事实与人工稿保留。');await refreshMatter(m.id,selection);await read(m.id);});return true;},clear:()=>records.clear(),isDirty:()=>[...records.values()].some(r=>r.dirty)};
}
