const esc = (value) => String(value ?? '').replace(/[&<>"']/g,(char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function createReminderPreferences({getState,getElement,request,post,canAccess,refreshList,toast}) {
  let data = null,draft = null,open = false,error = null,reading = false,bound = false,attempted = false,expiryTimer;
  const expired = () => data?.mode === 'quiet' && data.quiet_until !== null && (!data.quiet_active || (Number.isFinite(Date.parse(data.quiet_until)) && Date.now() >= Date.parse(data.quiet_until)));
  const quietActive = () => data?.quiet_active === true && (data.quiet_until === null || (Number.isFinite(Date.parse(data.quiet_until)) && Date.now() < Date.parse(data.quiet_until)));
  const status = () => !data ? '设置尚未读取；当前不推定静默。' : quietActive() ? `仅本地列表汇总已静默${data.quiet_until ? `，本人明示截止 ${data.quiet_until}` : '，未设截止，直到本人恢复'}` : expired() ? '本人明示静默截止已过／当前不生效；列表正常显示到时汇总。' : '本地列表正常显示到时汇总。';
  function scheduleExpiry() {clearTimeout(expiryTimer);if (!quietActive() || !data.quiet_until) return;const epoch = getState().identityEpoch,delay = Date.parse(data.quiet_until) - Date.now();expiryTimer = setTimeout(() => {if (epoch !== getState().identityEpoch || !canAccess()) return;refreshList();mount();scheduleExpiry();},Math.min(Math.max(delay + 20,20),2147483647));}
  function mount(force=false) {
    const container = getElement('#reminders-control');if (!container) return;container.hidden = !canAccess();if (!canAccess()) {container.innerHTML = '';return;}
    if (!bound) {container.addEventListener('toggle',(event) => {if (event.target.id === 'reminders-details' && event.target.isConnected) {open = event.target.open;if (open && !attempted && !reading) read();}},true);container.addEventListener('input',input);container.addEventListener('submit',(event) => {event.preventDefault();save();});container.addEventListener('click',(event) => {const button = event.target.closest('[data-reminders-read]');if (button && !button.disabled) read({adoptVersion:true});});bound = true;}
    if (!force && container.firstElementChild && (draft?.dirty || open || globalThis.document?.activeElement?.closest('#reminders-control'))) {const label = getElement('#reminders-status');if (label) label.textContent = status();for (const input of container.querySelectorAll('button,input,select')) input.disabled = Boolean(getState().busy || reading || (input.dataset.remindersField === 'quiet_until' && draft?.mode !== 'quiet'));return;}
    const disabled = getState().busy || reading ? 'disabled' : '';
    container.innerHTML = `<details id="reminders-details" class="local-reminders" ${open ? 'open' : ''}><summary class="details-toggle">本地提醒 · 仅列表汇总</summary><p id="reminders-status" class="small muted">${esc(status())}</p><p class="scope-note">${esc(data?.scope || '仅本人本地事项列表到时汇总，不隐藏事项内关键等待，不关闭事项、不暂停助理、不发送通知。')}</p>${error ? `<p class="small dirty-note">${esc(error)}</p>` : ''}<button class="button quiet" type="button" data-reminders-read ${disabled}>明确读取最新设置／差异</button>${draft ? `<form id="reminders-form"><label class="field-label" for="reminders-mode">本人本地列表提醒方式</label><select id="reminders-mode" data-reminders-field="mode" ${disabled}><option value="normal" ${draft.mode === 'normal' ? 'selected' : ''}>正常显示到时汇总</option><option value="quiet" ${draft.mode === 'quiet' ? 'selected' : ''}>仅列表到时汇总静默</option></select><label class="field-label" for="reminders-until">本人明确截止（可空＝直到本人恢复）</label><input id="reminders-until" data-reminders-field="quiet_until" value="${esc(draft.quiet_until || '')}" placeholder="2026-10-10T09:00:00+01:00" maxlength="100" ${disabled || draft.mode !== 'quiet' ? 'disabled' : ''}><p class="small muted">须明确含UTC偏移的ISO时间；不猜时区、不默认截止。保存基版 ${esc(draft.baseVersion)}，当前已读版本 ${esc(data.version)}。${draft.dirty ? '未保存选择保留；后台不会自动推进基版。' : ''}</p>${draft.dirty ? `<p class="small muted">服务器已存：${data.mode === 'quiet' ? '仅列表静默' : '正常显示'} · 截止 ${esc(data.quiet_until || '未设')}。读取按钮由本人明确采用已读保存版本，草稿选择仍保留。</p>` : ''}<button class="button" type="submit" ${disabled}>保存本地提醒设置</button><p id="reminders-saved-label" class="small ${draft.dirty ? 'dirty-note' : 'muted'}">${draft.dirty ? '有未保存设置' : '当前显示已存设置'}</p></form>` : '<p class="small muted">打开或明确读取后再按本人需要设置；未读取不假设已静默。</p>'}</details>`;
  }
  async function read({adoptVersion=false}={}) {
    if (!canAccess() || reading) return;const epoch = getState().identityEpoch;reading = true;attempted = true;mount(true);
    try {const fresh = await request('/api/reminder-preferences');if (epoch !== getState().identityEpoch || !canAccess()) return;data = fresh;error = null;scheduleExpiry();if (!draft?.dirty) draft = {mode:fresh.mode,quiet_until:fresh.quiet_until,baseVersion:fresh.version,dirty:false};else if (adoptVersion) draft.baseVersion = fresh.version;refreshList();}
    catch (failure) {if (epoch === getState().identityEpoch) error = failure.message || '提醒设置暂未读回；不假设已静默，人工选择保留。';}
    finally {if (epoch === getState().identityEpoch) {reading = false;mount(true);}}
  }
  function input(event) {const field = event.target.dataset.remindersField;if (!draft || !field) return;draft[field] = field === 'quiet_until' ? event.target.value || null : event.target.value;draft.dirty = true;if (field === 'mode') {if (draft.mode === 'normal') draft.quiet_until = null;const input = getElement('#reminders-until');if (input) {input.disabled = draft.mode !== 'quiet';input.value = draft.quiet_until || '';}}const label = getElement('#reminders-saved-label');if (label) {label.textContent = '有未保存设置，列表仍按原已存设置显示';label.classList.add('dirty-note');}}
  async function save() {
    if (!canAccess() || !draft || getState().busy) return;
    if (draft.mode === 'quiet' && draft.quiet_until && !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})$/.test(draft.quiet_until)) {toast('静默截止须有明确UTC偏移的ISO时间；不确定可留空，直到本人恢复。');return;}
    const epoch = getState().identityEpoch;let saved = false;
    await post('/api/reminder-preferences',{expected_version:draft.baseVersion,mode:draft.mode,quiet_until:draft.mode === 'normal' ? null : draft.quiet_until},(fresh) => {if (epoch !== getState().identityEpoch) return;saved = true;data = fresh;scheduleExpiry();draft = {mode:fresh.mode,quiet_until:fresh.quiet_until,baseVersion:fresh.version,dirty:false};error = null;mount(true);refreshList();toast('已保存本人本地列表提醒设置，事项内等待仍可见，未暂停或发送通知。');});
    if (!saved && epoch === getState().identityEpoch) {error = '本次保存未确认，原选择保留；请查看工作区错误并明确读取最新设置后核对。';mount(true);}
  }
  return {mount,read,quietActive,isDirty:() => Boolean(draft?.dirty),clear:() => {clearTimeout(expiryTimer);data = null;draft = null;open = false;error = null;reading = false;attempted = false;const container = getElement('#reminders-control');if (container) {container.innerHTML = '';container.hidden = true;}}};
}
